import numpy as np
array1 = np.array([[[1,2,3],[4,7,1],[8,4,1]]])
array2 = np.array([[[1,1,9],[1,4,6],[9,4,6]]])
print("array1 : ", array1)
print("array2 : ", array2)
print("--------------------------------------------------------")
print("array1 + array2 = ", array1+array2 )
print("--------------------------------------------------------")
print("array1 - array2 = ", array1-array2 )
print("--------------------------------------------------------")
print("array1 * array2 = ", array1*array2 )
print("--------------------------------------------------------")
print("array1 / array2 = ", array1/array2 )
print("--------------------------------------------------------")
print("array1 % array2 = ", array1%array2 )
print("--------------------------------------------------------")
print("array1 ** array2 = ", array1**array2 )
print("--------------------------------------------------------")
print("Matrix Multiplication", array1@array2)
print("--------------------------------------------------------")
print("Transpose 1", np.transpose(array1) )
print("--------------------------------------------------------")
print("Transpose 1", array1.transpose() )