import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("1-D Array : ", arr1)
print("2-D Array : ", arr2)
print("3-D Array : ", arr3)
print("------------------------------Size of Array--------------------------------")
print("Size of arr1 :", arr1.size)
print("Size of arr2 :", arr2.size)
print("Size of arr3 :", arr3.size)
print("----------------------------Dimensions of Array----------------------------")
print("Dimensions of arr1 :", arr1.ndim)
print("Dimensions of arr2 :", arr2.ndim)
print("Dimensions of arr3 :", arr3.ndim)
print("----------------------------Data Type of Array-----------------------------")
print("DataType of arr1 :", arr1.dtype)
print("DataType of arr2 :", arr2.dtype)
print("DataType of arr3 :", arr3.dtype)
print("-------------------------------Type of Array-------------------------------")
print("Type of arr1 :", type(arr1))
print("Type of arr2 :", type(arr2))
print("Type of arr3 :", type(arr3))
print("-------------------------------Shape of Array------------------------------")
print("Shape of arr1 :", arr1.shape)
print("Shape of arr2 :", arr2.shape)
print("Shape of arr3 :", arr3.shape)